version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "nix"
    directory: "/cv"
    schedule:
      interval: "monthly"
    groups:
      nix:
        patterns:
          - "*"
