line-length = 100
target-version = "py313"

[format]
quote-style = "double"

[lint]
select = ["E", "F", "I", "W", "ANN", "C90", "N", "SIM", "PERF", "RUF", "UP", "ARG", "S"]

[lint.per-file-ignores]
"__init__.py" = ["ANN"]
"tests/*" = ["ANN", "ARG", "S"]

[lint.mccabe]
max-complexity = 10
